### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading 'type')`

### ISSUE THREAD

**Issue by SettingDust** [lazyloong/obsidian-fuzzy-chinese#16]
双链出现报错，随机出现，不能稳定复现
```
app.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at FB (app.js:1:1464625)
    at t.selectSuggestion (app.js:1:1474218)
    at eval (plugin:fuzzy-chinese-pinyin:2:21402)
```

**Comment by lazyloong** [comment]
更新了2.6.2版，请尝试一下
