### ISSUE TITLE
与白板好像有冲突，修改卡片文字时，会弹出错误提示

### ISSUE THREAD

**Issue by a492038600** [lazyloong/obsidian-fuzzy-chinese#61]
在白板canvas中，修改卡片中的文字时，会弹出错误提示：
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'path')
    at t.getFileCache (app.js:1:2010240)
    at Ur.onTrigger (plugin:fuzzy-chinese-pinyin:21:64396)
    at t.trigger (app.js:1:1622119)
    at e.trigger (app.js:1:2138353)
    at app.js:1:1396429
    at l (app.js:1:522936)
    at c (app.js:1:523052)
    
![1727081176681](https://github.com/user-attachments/assets/e0f46df5-10d0-4c68-a3c2-57ab43d024fd)

我的OB版本是1.6.7  插件版本是2.27.2

**Comment by lazyloong** [comment]
好了，请试试2.27.3版
