### ISSUE TITLE
[BUG]标签框不能正常显示。v2.27.8

### ISSUE THREAD

**Issue by YanCore** [lazyloong/obsidian-fuzzy-chinese#67]
标签框不能正常显示。版本号：v2.27.8
## 界面截图
![image](https://github.com/user-attachments/assets/ddc73d6b-6e5c-46b9-b933-912a5ec6a26f)

## 日志
```
app.js:1 TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at new Ca (plugin:fuzzy-chinese-pinyin:21:36855)
    at new Dn (plugin:fuzzy-chinese-pinyin:21:38975)
    at new ql (plugin:fuzzy-chinese-pinyin:21:52018)
    at kr.addTagInput (plugin:fuzzy-chinese-pinyin:21:43168)
    at kr.onOpen (plugin:fuzzy-chinese-pinyin:21:43399)
    at e.open (app.js:1:1304660)
    at Object.callback (plugin:fuzzy-chinese-pinyin:24:7988)
    at ZU (app.js:1:1935452)
    at e.executeCommand (app.js:1:1937023)
    at e.eval (plugin:dbfolder:491:3722)
    at e.i [as executeCommand] (plugin:dbfolder:487:75925)
    at e.executeCommandById (app.js:1:1936930)
    at Object.eval [as func] (plugin:at-symbol-linking:3139:29)
    at e.handleKey (app.js:1:754621)
    at e.handleKey (app.js:1:754734)
    at t.handleKey (app.js:1:754943)
    at e.onKeyEvent (app.js:1:755877)
```

![image](https://github.com/user-attachments/assets/2e689a53-df97-4eb9-9dcc-342d39cdb1c6)

![image](https://github.com/user-attachments/assets/c079dbfc-12d6-46fc-a3d8-77cbea773f63)

![image](https://github.com/user-attachments/assets/1102f82e-f043-47b8-95a1-23e7527db9d1)

**Comment by YanCore** [comment]
看了下对应到这个代码文件```src/utils/pinyinSuggest.ts```。这部分代码：
```typescript
export class PinyinSuggest extends TextInputSuggest<MatchData<Item>> {
    getItemFunction: (query: string) => MatchData<Item>[];
    plugin: ThePlugin;
    constructor(inputEl: HTMLInputElement | HTMLTextAreaElement, plugin: ThePlugin) {
        super(inputEl);
        this.plugin = plugin;
    }
}
```
应该和Obsidian版本关系不大吧。目前Obsidian版本：v1.7.6。

**Comment by YanCore** [comment]
试了下直接改JS可以显示。源码应该改这部分。要么你忘记了，要么Obsidian更新接口了。 期待你的更新。

```typescript
export class PinyinSuggest extends TextInputSuggest<MatchData<Item>> {
    constructor(inputEl: HTMLInputElement | HTMLTextAreaElement, plugin: ThePlugin) {

        super(plugin,inputEl);

        this.plugin = plugin;
    }
}
```

**Comment by lazyloong** [comment]
确实是接口变了，不过不是 ob 的接口，引用了某个插件里的代码。2.27.9应该行了
